// Mock data for testing and demonstration purposes
export const mockData = {
  // USER ACCOUNTS
  userAccounts: [
    {
      userId: 'user001',
      username: 'user@demo.com',
      password: 'demo123',
      role: 'User',
    },
  ],

  // ADMINS
  admins: [
    {
      adminId: 'admin001',
      userId: 'admin001',
      username: 'admin@demo.com',
      adminName: 'Admin User',
      email: 'admin@demo.com',
      password: 'admin123',
    },
  ],

  // COACHES
  coaches: [
    {
      coachId: 'C001',
      coachName: 'Erik ten Hag',
      contact: '+44 161 868 8000',
      experience: 15,
    },
    {
      coachId: 'C002',
      coachName: 'Jurgen Klopp',
      contact: '+44 151 260 6677',
      experience: 23,
    },
    {
      coachId: 'C003',
      coachName: 'Pep Guardiola',
      contact: '+44 161 444 1894',
      experience: 17,
    },
    {
      coachId: 'C004',
      coachName: 'Mikel Arteta',
      contact: '+44 207 619 5000',
      experience: 5,
    },
    {
      coachId: 'C005',
      coachName: 'Mauricio Pochettino',
      contact: '+44 207 385 5545',
      experience: 16,
    },
  ],

  // REFEREES
  referees: [
    {
      refereeId: 'R001',
      refereeName: 'Michael Oliver',
      contact: '+44 191 222 1000',
      availabilityStatus: 'Available',
    },
    {
      refereeId: 'R002',
      refereeName: 'Andre Marriner',
      contact: '+44 121 222 1000',
      availabilityStatus: 'Available',
    },
    {
      refereeId: 'R003',
      refereeName: 'Craig Pawson',
      contact: '+44 114 222 1000',
      availabilityStatus: 'Available',
    },
    {
      refereeId: 'R004',
      refereeName: 'Martin Atkinson',
      contact: '+44 113 222 1000',
      availabilityStatus: 'Unavailable',
    },
  ],

  // LEAGUES
  leagues: [
    {
      id: 1,
      leagueId: 'L001',
      adminId: 'admin001',
      name: 'Premier League 2024',
      leagueName: 'Premier League 2024',
      description: 'Top tier professional sports league',
      season: 2024,
      status: 'active',
      country: 'England',
      teams: [1, 2, 3, 4, 5],
      totalTeams: 20,
      startDate: '2024-08-10',
      endDate: '2025-05-25',
    },
    {
      id: 2,
      leagueId: 'L002',
      adminId: 'admin001',
      name: 'Championship 2024',
      leagueName: 'Championship 2024',
      description: 'Second tier professional league',
      season: 2024,
      status: 'active',
      country: 'England',
      teams: [6, 7, 8, 9, 10],
      totalTeams: 24,
      startDate: '2024-08-10',
      endDate: '2025-05-25',
    },
  ],

  // TOURNAMENTS
  tournaments: [
    {
      id: 1,
      tournamentId: 'T001',
      adminId: 'admin001',
      name: 'FA Cup 2024',
      tournamentName: 'FA Cup 2024',
      description: 'National knockout tournament',
      startDate: '2024-11-01',
      endDate: '2025-05-31',
      status: 'ongoing',
      teams: [1, 2, 3, 4, 5],
      totalTeams: 64,
      league: 1,
    },
    {
      id: 2,
      tournamentId: 'T002',
      adminId: 'admin001',
      name: 'League Cup 2024',
      tournamentName: 'League Cup 2024',
      description: 'Domestic cup competition',
      startDate: '2024-08-15',
      endDate: '2025-03-02',
      status: 'ongoing',
      teams: [1, 2, 3, 4],
      totalTeams: 92,
      league: 1,
    },
  ],

  // TOURNAMENT-TEAM junction table
  tournamentTeams: [
    { tournamentTeamId: 'TT001', tournamentId: 'T001', teamId: 'TEAM001' },
    { tournamentTeamId: 'TT002', tournamentId: 'T001', teamId: 'TEAM002' },
    { tournamentTeamId: 'TT003', tournamentId: 'T001', teamId: 'TEAM003' },
    { tournamentTeamId: 'TT004', tournamentId: 'T001', teamId: 'TEAM004' },
    { tournamentTeamId: 'TT005', tournamentId: 'T001', teamId: 'TEAM005' },
    { tournamentTeamId: 'TT006', tournamentId: 'T002', teamId: 'TEAM001' },
    { tournamentTeamId: 'TT007', tournamentId: 'T002', teamId: 'TEAM002' },
    { tournamentTeamId: 'TT008', tournamentId: 'T002', teamId: 'TEAM003' },
    { tournamentTeamId: 'TT009', tournamentId: 'T002', teamId: 'TEAM004' },
  ],

  // TEAMS
  teams: [
    {
      id: 1,
      teamId: 'TEAM001',
      leagueId: 'L001',
      coachId: 'C001',
      name: 'Manchester United',
      abbreviation: 'MAN',
      city: 'Manchester',
      founded: 1878,
      stadium: 'Old Trafford',
      coach: 'Erik ten Hag',
      players: [1, 2, 3, 4, 5],
      totalPlayers: 25,
      league: 1,
      wins: 15,
      losses: 3,
      draws: 2,
    },
    {
      id: 2,
      teamId: 'TEAM002',
      leagueId: 'L001',
      coachId: 'C002',
      name: 'Liverpool FC',
      abbreviation: 'LIV',
      city: 'Liverpool',
      founded: 1892,
      stadium: 'Anfield',
      coach: 'Jurgen Klopp',
      players: [6, 7, 8, 9, 10],
      totalPlayers: 25,
      league: 1,
      wins: 16,
      losses: 2,
      draws: 2,
    },
    {
      id: 3,
      teamId: 'TEAM003',
      leagueId: 'L001',
      coachId: 'C003',
      name: 'Manchester City',
      abbreviation: 'MCI',
      city: 'Manchester',
      founded: 1880,
      stadium: 'Etihad Stadium',
      coach: 'Pep Guardiola',
      players: [11, 12, 13, 14, 15],
      totalPlayers: 25,
      league: 1,
      wins: 17,
      losses: 1,
      draws: 2,
    },
    {
      id: 4,
      teamId: 'TEAM004',
      leagueId: 'L001',
      coachId: 'C004',
      name: 'Arsenal FC',
      abbreviation: 'ARS',
      city: 'London',
      founded: 1886,
      stadium: 'Emirates Stadium',
      coach: 'Mikel Arteta',
      players: [16, 17, 18, 19, 20],
      totalPlayers: 24,
      league: 1,
      wins: 14,
      losses: 4,
      draws: 2,
    },
    {
      id: 5,
      teamId: 'TEAM005',
      leagueId: 'L001',
      coachId: 'C005',
      name: 'Chelsea FC',
      abbreviation: 'CHE',
      city: 'London',
      founded: 1905,
      stadium: 'Stamford Bridge',
      coach: 'Mauricio Pochettino',
      players: [21, 22, 23, 24, 25],
      totalPlayers: 24,
      league: 1,
      wins: 13,
      losses: 5,
      draws: 2,
    },
  ],

  // TEAM STATS (league-specific)
  teamStats: [
    {
      leagueStatsId: 'LS001',
      leagueId: 'L001',
      teamId: 'TEAM001',
    },
    {
      leagueStatsId: 'LS002',
      leagueId: 'L001',
      teamId: 'TEAM002',
    },
    {
      leagueStatsId: 'LS003',
      leagueId: 'L001',
      teamId: 'TEAM003',
    },
    {
      leagueStatsId: 'LS004',
      leagueId: 'L001',
      teamId: 'TEAM004',
    },
    {
      leagueStatsId: 'LS005',
      leagueId: 'L001',
      teamId: 'TEAM005',
    },
  ],

  // PLAYERS
  players: [
    {
      id: 1,
      playerId: 'P001',
      teamId: 'TEAM001',
      name: 'Cristiano Ronaldo',
      playerName: 'Cristiano Ronaldo',
      number: 7,
      position: 'Forward',
      nationality: 'Portuguese',
      age: 39,
      height: 187,
      weight: 84,
      team: 1,
      marketValue: 50000000,
      goals: 22,
      assists: 3,
      appearances: 28,
      contractDetails: 'Contract until 2025',
    },
    {
      id: 2,
      playerId: 'P002',
      teamId: 'TEAM001',
      name: 'Bruno Fernandes',
      playerName: 'Bruno Fernandes',
      number: 8,
      position: 'Midfielder',
      nationality: 'Portuguese',
      age: 29,
      height: 188,
      weight: 80,
      team: 1,
      marketValue: 85000000,
      goals: 8,
      assists: 12,
      appearances: 25,
      contractDetails: 'Contract until 2026',
    },
    {
      id: 3,
      playerId: 'P003',
      teamId: 'TEAM001',
      name: 'Jadon Sancho',
      playerName: 'Jadon Sancho',
      number: 25,
      position: 'Winger',
      nationality: 'English',
      age: 24,
      height: 180,
      weight: 74,
      team: 1,
      marketValue: 65000000,
      goals: 5,
      assists: 4,
      appearances: 18,
      contractDetails: 'Contract until 2026',
    },
    {
      id: 4,
      playerId: 'P004',
      teamId: 'TEAM001',
      name: 'Lisandro Martinez',
      playerName: 'Lisandro Martinez',
      number: 6,
      position: 'Defender',
      nationality: 'Argentine',
      age: 26,
      height: 189,
      weight: 82,
      team: 1,
      marketValue: 55000000,
      goals: 1,
      assists: 0,
      appearances: 22,
      contractDetails: 'Contract until 2027',
    },
    {
      id: 5,
      playerId: 'P005',
      teamId: 'TEAM001',
      name: 'Andre Onana',
      playerName: 'Andre Onana',
      number: 24,
      position: 'Goalkeeper',
      nationality: 'Cameroonian',
      age: 28,
      height: 189,
      weight: 86,
      team: 1,
      marketValue: 60000000,
      goals: 0,
      assists: 0,
      appearances: 28,
      contractDetails: 'Contract until 2028',
    },
    {
      id: 6,
      playerId: 'P006',
      teamId: 'TEAM002',
      name: 'Mohamed Salah',
      playerName: 'Mohamed Salah',
      number: 11,
      position: 'Forward',
      nationality: 'Egyptian',
      age: 32,
      height: 175,
      weight: 78,
      team: 2,
      marketValue: 75000000,
      goals: 19,
      assists: 6,
      appearances: 26,
      contractDetails: 'Contract until 2025',
    },
    {
      id: 7,
      playerId: 'P007',
      teamId: 'TEAM002',
      name: 'Virgil van Dijk',
      playerName: 'Virgil van Dijk',
      number: 4,
      position: 'Defender',
      nationality: 'Dutch',
      age: 33,
      height: 193,
      weight: 92,
      team: 2,
      marketValue: 65000000,
      goals: 0,
      assists: 0,
      appearances: 24,
      contractDetails: 'Contract until 2025',
    },
  ],

  // PLAYER STATS
  playerStats: [
    {
      statsId: 'PS001',
      playerId: 'P001',
      matchesPlayed: 28,
      wins: 15,
      goalsOrRuns: 22,
      assists: 3,
      rating: 8.5,
    },
    {
      statsId: 'PS002',
      playerId: 'P002',
      matchesPlayed: 25,
      wins: 14,
      goalsOrRuns: 8,
      assists: 12,
      rating: 8.2,
    },
    {
      statsId: 'PS003',
      playerId: 'P003',
      matchesPlayed: 18,
      wins: 10,
      goalsOrRuns: 5,
      assists: 4,
      rating: 7.5,
    },
    {
      statsId: 'PS004',
      playerId: 'P004',
      matchesPlayed: 22,
      wins: 12,
      goalsOrRuns: 1,
      assists: 0,
      rating: 7.8,
    },
    {
      statsId: 'PS005',
      playerId: 'P005',
      matchesPlayed: 28,
      wins: 15,
      goalsOrRuns: 0,
      assists: 0,
      rating: 7.9,
    },
    {
      statsId: 'PS006',
      playerId: 'P006',
      matchesPlayed: 26,
      wins: 16,
      goalsOrRuns: 19,
      assists: 6,
      rating: 8.7,
    },
    {
      statsId: 'PS007',
      playerId: 'P007',
      matchesPlayed: 24,
      wins: 15,
      goalsOrRuns: 0,
      assists: 0,
      rating: 8.0,
    },
  ],

  // VENUES
  venues: [
    {
      id: 1,
      venueId: 'V001',
      name: 'Old Trafford',
      venueName: 'Old Trafford',
      city: 'Manchester',
      country: 'England',
      location: 'Manchester, England',
      capacity: 74310,
      opened: 1910,
      team: 1,
      surface: 'Grass',
      lights: true,
      coordinates: { lat: 53.463, lng: -2.291 },
      availableEvents: 5,
      isAvailable: true,
    },
    {
      id: 2,
      venueId: 'V002',
      name: 'Anfield',
      venueName: 'Anfield',
      city: 'Liverpool',
      country: 'England',
      location: 'Liverpool, England',
      capacity: 61294,
      opened: 1884,
      team: 2,
      surface: 'Grass',
      lights: true,
      coordinates: { lat: 53.431, lng: -2.961 },
      availableEvents: 3,
      isAvailable: true,
    },
    {
      id: 3,
      venueId: 'V003',
      name: 'Etihad Stadium',
      venueName: 'Etihad Stadium',
      city: 'Manchester',
      country: 'England',
      location: 'Manchester, England',
      capacity: 55097,
      opened: 2003,
      team: 3,
      surface: 'Grass',
      lights: true,
      coordinates: { lat: 53.583, lng: -2.200 },
      availableEvents: 4,
      isAvailable: true,
    },
    {
      id: 4,
      venueId: 'V004',
      name: 'Emirates Stadium',
      venueName: 'Emirates Stadium',
      city: 'London',
      country: 'England',
      location: 'London, England',
      capacity: 60704,
      opened: 2006,
      team: 4,
      surface: 'Grass',
      lights: true,
      coordinates: { lat: 51.555, lng: -0.108 },
      availableEvents: 6,
      isAvailable: true,
    },
    {
      id: 5,
      venueId: 'V005',
      name: 'Stamford Bridge',
      venueName: 'Stamford Bridge',
      city: 'London',
      country: 'England',
      location: 'London, England',
      capacity: 40341,
      opened: 1877,
      team: 5,
      surface: 'Grass',
      lights: true,
      coordinates: { lat: 51.482, lng: -0.191 },
      availableEvents: 5,
      isAvailable: true,
    },
  ],

  // MATCHES
  matches: [
    {
      id: 1,
      matchId: 'M001',
      leagueId: 'L001',
      tournamentId: 'T001',
      venueId: 'V001',
      refereeId: 'R001',
      homeTeam: 1,
      awayTeam: 2,
      homeTeamName: 'Manchester United',
      awayTeamName: 'Liverpool FC',
      date: '2024-12-26',
      matchDate: '2024-12-26',
      time: '20:00',
      matchTime: '20:00',
      venue: 1,
      status: 'scheduled',
      homeScore: null,
      awayScore: null,
      teamScore: null,
      team2Score: null,
      tournament: 1,
      attendance: null,
      referee: 'Michael Oliver',
      winnerTeamId: null,
      highlights: null,
    },
    {
      id: 2,
      matchId: 'M002',
      leagueId: 'L001',
      tournamentId: 'T001',
      venueId: 'V003',
      refereeId: 'R002',
      homeTeam: 3,
      awayTeam: 4,
      homeTeamName: 'Manchester City',
      awayTeamName: 'Arsenal FC',
      date: '2024-12-27',
      matchDate: '2024-12-27',
      time: '19:30',
      matchTime: '19:30',
      venue: 3,
      status: 'scheduled',
      homeScore: null,
      awayScore: null,
      teamScore: null,
      team2Score: null,
      tournament: 1,
      attendance: null,
      referee: 'Andre Marriner',
      winnerTeamId: null,
      highlights: null,
    },
    {
      id: 3,
      matchId: 'M003',
      leagueId: 'L001',
      tournamentId: 'T001',
      venueId: 'V002',
      refereeId: 'R003',
      homeTeam: 2,
      awayTeam: 5,
      homeTeamName: 'Liverpool FC',
      awayTeamName: 'Chelsea FC',
      date: '2024-12-28',
      matchDate: '2024-12-28',
      time: '15:00',
      matchTime: '15:00',
      venue: 2,
      status: 'scheduled',
      homeScore: null,
      awayScore: null,
      teamScore: null,
      team2Score: null,
      tournament: 1,
      attendance: null,
      referee: 'Craig Pawson',
      winnerTeamId: null,
      highlights: null,
    },
    {
      id: 4,
      matchId: 'M004',
      leagueId: 'L001',
      tournamentId: 'T001',
      venueId: 'V001',
      refereeId: 'R004',
      homeTeam: 1,
      awayTeam: 3,
      homeTeamName: 'Manchester United',
      awayTeamName: 'Manchester City',
      date: '2024-12-10',
      matchDate: '2024-12-10',
      time: '16:30',
      matchTime: '16:30',
      venue: 1,
      status: 'completed',
      homeScore: 2,
      awayScore: 1,
      teamScore: 2,
      team2Score: 1,
      tournament: 1,
      attendance: 74310,
      referee: 'Martin Atkinson',
      winnerTeamId: 'TEAM001',
      highlights: 'Great match with exciting goals',
    },
  ],

  statistics: {
    totalMatches: 4,
    totalTeams: 20,
    totalPlayers: 500,
    totalLeagues: 2,
    totalVenues: 10,
    matchesToday: 1,
    upcomingMatches: 3,
  },

  // TRANSFERS (TRANSFERDETAILS)
  transfers: [
    {
      id: 1,
      transferDetailsId: 'TD001',
      transferId: 'TR001',
      playerId: 'P006',
      leagueId: 'L001',
      fromTeamId: 'TEAM002',
      toTeamId: 'TEAM001',
      playerName: 'Mohamed Salah',
      fromTeam: 2,
      toTeam: 1,
      fromTeamName: 'Liverpool FC',
      toTeamName: 'Manchester United',
      transferDate: '2024-08-31',
      transferFee: 100000000,
      transferType: 'Permanent',
      status: 'completed',
      season: 2024,
    },
    {
      id: 2,
      transferDetailsId: 'TD002',
      transferId: 'TR002',
      playerId: 'P003',
      leagueId: 'L001',
      fromTeamId: 'TEAM004',
      toTeamId: 'TEAM001',
      playerName: 'Jadon Sancho',
      fromTeam: 4,
      toTeam: 1,
      fromTeamName: 'Arsenal FC',
      toTeamName: 'Manchester United',
      transferDate: '2024-08-15',
      transferFee: 65000000,
      transferType: 'Permanent',
      status: 'completed',
      season: 2024,
    },
  ],

  reports: [
    {
      id: 1,
      matchId: 1,
      reportType: 'Match Report',
      title: 'Manchester United vs Liverpool - Match Summary',
      content: 'Detailed match analysis and highlights',
      generatedBy: 'admin@demo.com',
      generatedDate: '2024-12-26',
      status: 'published',
    },
    {
      id: 2,
      matchId: 2,
      reportType: 'Injury Report',
      title: 'Player Injuries - Week 15',
      content: 'Summary of injuries affecting upcoming matches',
      generatedBy: 'admin@demo.com',
      generatedDate: '2024-12-20',
      status: 'published',
    },
  ],
};

// Backward compatibility: populate playerTransfers from transfers
mockData.playerTransfers = mockData.transfers;

// Get all data
export const getAllData = () => mockData;

// Get specific data by type
export const getDataByType = (type) => mockData[type] || [];

// Get single item by ID
export const getItemById = (type, id) => {
  const items = mockData[type] || [];
  return items.find(item => item.id === id);
};

// Search items
export const searchItems = (type, searchTerm) => {
  const items = mockData[type] || [];
  return items.filter(item =>
    Object.values(item).some(value =>
      String(value).toLowerCase().includes(searchTerm.toLowerCase())
    )
  );
};

// Get statistics
export const getStatistics = () => {
  return {
    leagues: mockData.leagues.length,
    tournaments: mockData.tournaments.length,
    teams: mockData.teams.length,
    players: mockData.players.length,
    venues: mockData.venues.length,
    matches: mockData.matches.length,
    upcomingMatches: mockData.matches.filter(m => m.status === 'scheduled').length,
    completedMatches: mockData.matches.filter(m => m.status === 'completed').length,
  };
};
