// Mock data for testing and demonstration purposes
export const mockData = {
  leagues: [
    {
      id: 1,
      name: 'Premier League 2024',
      description: 'Top tier professional sports league',
      season: 2024,
      status: 'active',
      country: 'England',
      teams: [1, 2, 3, 4, 5],
      totalTeams: 20,
    },
    {
      id: 2,
      name: 'Championship 2024',
      description: 'Second tier professional league',
      season: 2024,
      status: 'active',
      country: 'England',
      teams: [6, 7, 8, 9, 10],
      totalTeams: 24,
    },
  ],

  tournaments: [
    {
      id: 1,
      name: 'FA Cup 2024',
      description: 'National knockout tournament',
      startDate: '2024-11-01',
      endDate: '2024-05-31',
      status: 'ongoing',
      teams: [1, 2, 3, 4, 5],
      totalTeams: 64,
      league: 1,
    },
    {
      id: 2,
      name: 'League Cup 2024',
      description: 'Domestic cup competition',
      startDate: '2024-08-15',
      endDate: '2024-03-02',
      status: 'ongoing',
      teams: [1, 2, 3, 4],
      totalTeams: 92,
      league: 1,
    },
  ],

  teams: [
    {
      id: 1,
      name: 'Manchester United',
      abbreviation: 'MAN',
      city: 'Manchester',
      founded: 1878,
      stadium: 'Old Trafford',
      coach: 'Erik ten Hag',
      players: [1, 2, 3, 4, 5],
      totalPlayers: 25,
      league: 1,
      wins: 15,
      losses: 3,
      draws: 2,
    },
    {
      id: 2,
      name: 'Liverpool FC',
      abbreviation: 'LIV',
      city: 'Liverpool',
      founded: 1892,
      stadium: 'Anfield',
      coach: 'Jurgen Klopp',
      players: [6, 7, 8, 9, 10],
      totalPlayers: 25,
      league: 1,
      wins: 16,
      losses: 2,
      draws: 2,
    },
    {
      id: 3,
      name: 'Manchester City',
      abbreviation: 'MCI',
      city: 'Manchester',
      founded: 1880,
      stadium: 'Etihad Stadium',
      coach: 'Pep Guardiola',
      players: [11, 12, 13, 14, 15],
      totalPlayers: 25,
      league: 1,
      wins: 17,
      losses: 1,
      draws: 2,
    },
    {
      id: 4,
      name: 'Arsenal FC',
      abbreviation: 'ARS',
      city: 'London',
      founded: 1886,
      stadium: 'Emirates Stadium',
      coach: 'Mikel Arteta',
      players: [16, 17, 18, 19, 20],
      totalPlayers: 24,
      league: 1,
      wins: 14,
      losses: 4,
      draws: 2,
    },
    {
      id: 5,
      name: 'Chelsea FC',
      abbreviation: 'CHE',
      city: 'London',
      founded: 1905,
      stadium: 'Stamford Bridge',
      coach: 'Mauricio Pochettino',
      players: [21, 22, 23, 24, 25],
      totalPlayers: 24,
      league: 1,
      wins: 13,
      losses: 5,
      draws: 2,
    },
  ],

  players: [
    {
      id: 1,
      name: 'Cristiano Ronaldo',
      number: 7,
      position: 'Forward',
      nationality: 'Portuguese',
      age: 39,
      height: 187,
      weight: 84,
      team: 1,
      marketValue: 50000000,
      goals: 22,
      assists: 3,
      appearances: 28,
    },
    {
      id: 2,
      name: 'Bruno Fernandes',
      number: 8,
      position: 'Midfielder',
      nationality: 'Portuguese',
      age: 29,
      height: 188,
      weight: 80,
      team: 1,
      marketValue: 85000000,
      goals: 8,
      assists: 12,
      appearances: 25,
    },
    {
      id: 3,
      name: 'Jadon Sancho',
      number: 25,
      position: 'Winger',
      nationality: 'English',
      age: 24,
      height: 180,
      weight: 74,
      team: 1,
      marketValue: 65000000,
      goals: 5,
      assists: 4,
      appearances: 18,
    },
    {
      id: 4,
      name: 'Lisandro Martinez',
      number: 6,
      position: 'Defender',
      nationality: 'Argentine',
      age: 26,
      height: 189,
      weight: 82,
      team: 1,
      marketValue: 55000000,
      goals: 1,
      assists: 0,
      appearances: 22,
    },
    {
      id: 5,
      name: 'Andre Onana',
      number: 24,
      position: 'Goalkeeper',
      nationality: 'Cameroonian',
      age: 28,
      height: 189,
      weight: 86,
      team: 1,
      marketValue: 60000000,
      goals: 0,
      assists: 0,
      appearances: 28,
    },
    {
      id: 6,
      name: 'Mohamed Salah',
      number: 11,
      position: 'Forward',
      nationality: 'Egyptian',
      age: 32,
      height: 175,
      weight: 78,
      team: 2,
      marketValue: 75000000,
      goals: 19,
      assists: 6,
      appearances: 26,
    },
    {
      id: 7,
      name: 'Virgil van Dijk',
      number: 4,
      position: 'Defender',
      nationality: 'Dutch',
      age: 33,
      height: 193,
      weight: 92,
      team: 2,
      marketValue: 65000000,
      goals: 0,
      assists: 0,
      appearances: 24,
    },
  ],

  venues: [
    {
      id: 1,
      name: 'Old Trafford',
      city: 'Manchester',
      country: 'England',
      capacity: 74310,
      opened: 1910,
      team: 1,
      surface: 'Grass',
      lights: true,
      coordinates: { lat: 53.463, lng: -2.291 },
      availableEvents: 5,
    },
    {
      id: 2,
      name: 'Anfield',
      city: 'Liverpool',
      country: 'England',
      capacity: 61294,
      opened: 1884,
      team: 2,
      surface: 'Grass',
      lights: true,
      coordinates: { lat: 53.431, lng: -2.961 },
      availableEvents: 3,
    },
    {
      id: 3,
      name: 'Etihad Stadium',
      city: 'Manchester',
      country: 'England',
      capacity: 55097,
      opened: 2003,
      team: 3,
      surface: 'Grass',
      lights: true,
      coordinates: { lat: 53.583, lng: -2.200 },
      availableEvents: 4,
    },
    {
      id: 4,
      name: 'Emirates Stadium',
      city: 'London',
      country: 'England',
      capacity: 60704,
      opened: 2006,
      team: 4,
      surface: 'Grass',
      lights: true,
      coordinates: { lat: 51.555, lng: -0.108 },
      availableEvents: 6,
    },
    {
      id: 5,
      name: 'Stamford Bridge',
      city: 'London',
      country: 'England',
      capacity: 40341,
      opened: 1877,
      team: 5,
      surface: 'Grass',
      lights: true,
      coordinates: { lat: 51.482, lng: -0.191 },
      availableEvents: 5,
    },
  ],

  matches: [
    {
      id: 1,
      homeTeam: 1,
      awayTeam: 2,
      homeTeamName: 'Manchester United',
      awayTeamName: 'Liverpool FC',
      date: '2024-12-26',
      time: '20:00',
      venue: 1,
      status: 'scheduled',
      homeScore: null,
      awayScore: null,
      tournament: 1,
      attendance: null,
      referee: 'Michael Oliver',
    },
    {
      id: 2,
      homeTeam: 3,
      awayTeam: 4,
      homeTeamName: 'Manchester City',
      awayTeamName: 'Arsenal FC',
      date: '2024-12-27',
      time: '19:30',
      venue: 3,
      status: 'scheduled',
      homeScore: null,
      awayScore: null,
      tournament: 1,
      attendance: null,
      referee: 'Andre Marriner',
    },
    {
      id: 3,
      homeTeam: 2,
      awayTeam: 5,
      homeTeamName: 'Liverpool FC',
      awayTeamName: 'Chelsea FC',
      date: '2024-12-28',
      time: '15:00',
      venue: 2,
      status: 'scheduled',
      homeScore: null,
      awayScore: null,
      tournament: 1,
      attendance: null,
      referee: 'Craig Pawson',
    },
    {
      id: 4,
      homeTeam: 1,
      awayTeam: 3,
      homeTeamName: 'Manchester United',
      awayTeamName: 'Manchester City',
      date: '2024-12-10',
      time: '16:30',
      venue: 1,
      status: 'completed',
      homeScore: 2,
      awayScore: 1,
      tournament: 1,
      attendance: 74310,
      referee: 'Martin Atkinson',
    },
  ],

  statistics: {
    totalMatches: 4,
    totalTeams: 20,
    totalPlayers: 500,
    totalLeagues: 2,
    totalVenues: 10,
    matchesToday: 1,
    upcomingMatches: 3,
  },

  playerTransfers: [
    {
      id: 1,
      playerId: 6,
      playerName: 'Mohamed Salah',
      fromTeam: 2,
      toTeam: 1,
      fromTeamName: 'Liverpool FC',
      toTeamName: 'Manchester United',
      transferDate: '2024-08-31',
      transferFee: 100000000,
      status: 'completed',
      season: 2024,
    },
    {
      id: 2,
      playerId: 3,
      playerName: 'Jadon Sancho',
      fromTeam: 4,
      toTeam: 1,
      fromTeamName: 'Arsenal FC',
      toTeamName: 'Manchester United',
      transferDate: '2024-08-15',
      transferFee: 65000000,
      status: 'completed',
      season: 2024,
    },
  ],

  reports: [
    {
      id: 1,
      matchId: 1,
      reportType: 'Match Report',
      title: 'Manchester United vs Liverpool - Match Summary',
      content: 'Detailed match analysis and highlights',
      generatedBy: 'admin@demo.com',
      generatedDate: '2024-12-26',
      status: 'published',
    },
    {
      id: 2,
      matchId: 2,
      reportType: 'Injury Report',
      title: 'Player Injuries - Week 15',
      content: 'Summary of injuries affecting upcoming matches',
      generatedBy: 'admin@demo.com',
      generatedDate: '2024-12-20',
      status: 'published',
    },
  ],
};

// Get all data
export const getAllData = () => mockData;

// Get specific data by type
export const getDataByType = (type) => mockData[type] || [];

// Get single item by ID
export const getItemById = (type, id) => {
  const items = mockData[type] || [];
  return items.find(item => item.id === id);
};

// Search items
export const searchItems = (type, searchTerm) => {
  const items = mockData[type] || [];
  return items.filter(item =>
    Object.values(item).some(value =>
      String(value).toLowerCase().includes(searchTerm.toLowerCase())
    )
  );
};

// Get statistics
export const getStatistics = () => {
  return {
    leagues: mockData.leagues.length,
    tournaments: mockData.tournaments.length,
    teams: mockData.teams.length,
    players: mockData.players.length,
    venues: mockData.venues.length,
    matches: mockData.matches.length,
    upcomingMatches: mockData.matches.filter(m => m.status === 'scheduled').length,
    completedMatches: mockData.matches.filter(m => m.status === 'completed').length,
  };
};
