-- Sports Management Database Schema

CREATE DATABASE IF NOT EXISTS sports_management_db;
USE sports_management_db;

-- USERACCOUNT Table
CREATE TABLE IF NOT EXISTS USERACCOUNT (
    UserID VARCHAR(50) PRIMARY KEY,
    Username VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role ENUM('User', 'Admin') NOT NULL DEFAULT 'User',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ADMIN Table
CREATE TABLE IF NOT EXISTS ADMIN (
    AdminID VARCHAR(50) PRIMARY KEY,
    UserID VARCHAR(50) NOT NULL,
    AdminName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USERACCOUNT(UserID) ON DELETE CASCADE
);

-- COACH Table
CREATE TABLE IF NOT EXISTS COACH (
    CoachID VARCHAR(50) PRIMARY KEY,
    CoachName VARCHAR(100) NOT NULL,
    Contact VARCHAR(50),
    Experience INT DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- REFEREE Table
CREATE TABLE IF NOT EXISTS REFEREE (
    RefereeID VARCHAR(50) PRIMARY KEY,
    RefereeName VARCHAR(100) NOT NULL,
    Contact VARCHAR(50),
    AvailabilityStatus ENUM('Available', 'Unavailable') DEFAULT 'Available',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- LEAGUE Table
CREATE TABLE IF NOT EXISTS LEAGUE (
    LeagueID VARCHAR(50) PRIMARY KEY,
    AdminID VARCHAR(50) NOT NULL,
    LeagueName VARCHAR(100) NOT NULL,
    StartDate DATE,
    EndDate DATE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AdminID) REFERENCES ADMIN(AdminID) ON DELETE CASCADE
);

-- TOURNAMENT Table
CREATE TABLE IF NOT EXISTS TOURNAMENT (
    TournamentID VARCHAR(50) PRIMARY KEY,
    AdminID VARCHAR(50) NOT NULL,
    TournamentName VARCHAR(100) NOT NULL,
    StartDate DATE,
    EndDate DATE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AdminID) REFERENCES ADMIN(AdminID) ON DELETE CASCADE
);

-- TEAM Table
CREATE TABLE IF NOT EXISTS TEAM (
    TeamID VARCHAR(50) PRIMARY KEY,
    LeagueID VARCHAR(50),
    CoachID VARCHAR(50),
    TeamName VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LeagueID) REFERENCES LEAGUE(LeagueID) ON DELETE SET NULL,
    FOREIGN KEY (CoachID) REFERENCES COACH(CoachID) ON DELETE SET NULL
);

-- TEAMSTATS Table (League-specific team statistics)
CREATE TABLE IF NOT EXISTS TEAMSTATS (
    LeagueStatsID VARCHAR(50) PRIMARY KEY,
    LeagueID VARCHAR(50) NOT NULL,
    TeamID VARCHAR(50) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LeagueID) REFERENCES LEAGUE(LeagueID) ON DELETE CASCADE,
    FOREIGN KEY (TeamID) REFERENCES TEAM(TeamID) ON DELETE CASCADE
);

-- TOURNAMENTTEAM Junction Table
CREATE TABLE IF NOT EXISTS TOURNAMENTTEAM (
    TournamentTeamID VARCHAR(50) PRIMARY KEY,
    TournamentID VARCHAR(50) NOT NULL,
    TeamID VARCHAR(50) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TournamentID) REFERENCES TOURNAMENT(TournamentID) ON DELETE CASCADE,
    FOREIGN KEY (TeamID) REFERENCES TEAM(TeamID) ON DELETE CASCADE,
    UNIQUE KEY unique_tournament_team (TournamentID, TeamID)
);

-- PLAYER Table
CREATE TABLE IF NOT EXISTS PLAYER (
    PlayerID VARCHAR(50) PRIMARY KEY,
    TeamID VARCHAR(50),
    PlayerName VARCHAR(100) NOT NULL,
    PlayerRole VARCHAR(50),
    ContractDetails TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TeamID) REFERENCES TEAM(TeamID) ON DELETE SET NULL
);

-- PLAYERSTATS Table
CREATE TABLE IF NOT EXISTS PLAYERSTATS (
    StatsID VARCHAR(50) PRIMARY KEY,
    PlayerID VARCHAR(50) NOT NULL,
    MatchesPlayed INT DEFAULT 0,
    Wins INT DEFAULT 0,
    GoalsOrRuns INT DEFAULT 0,
    Assists INT DEFAULT 0,
    Rating DECIMAL(3,1) DEFAULT 0.0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PlayerID) REFERENCES PLAYER(PlayerID) ON DELETE CASCADE
);

-- VENUE Table
CREATE TABLE IF NOT EXISTS VENUE (
    VenueID VARCHAR(50) PRIMARY KEY,
    VenueName VARCHAR(100) NOT NULL,
    Location VARCHAR(200),
    Capacity INT,
    IsAvailable BOOLEAN DEFAULT TRUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- MATCH Table
CREATE TABLE IF NOT EXISTS MATCH (
    MatchID VARCHAR(50) PRIMARY KEY,
    LeagueID VARCHAR(50),
    TournamentID VARCHAR(50),
    VenueID VARCHAR(50),
    RefereeID VARCHAR(50),
    MatchDate DATE,
    MatchTime TIME,
    Team1Score INT,
    Team2Score INT,
    Status VARCHAR(50) DEFAULT 'scheduled',
    WinnerTeamID VARCHAR(50),
    Highlights TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LeagueID) REFERENCES LEAGUE(LeagueID) ON DELETE SET NULL,
    FOREIGN KEY (TournamentID) REFERENCES TOURNAMENT(TournamentID) ON DELETE SET NULL,
    FOREIGN KEY (VenueID) REFERENCES VENUE(VenueID) ON DELETE SET NULL,
    FOREIGN KEY (RefereeID) REFERENCES REFEREE(RefereeID) ON DELETE SET NULL,
    FOREIGN KEY (WinnerTeamID) REFERENCES TEAM(TeamID) ON DELETE SET NULL
);

-- TRANSFER Table
CREATE TABLE IF NOT EXISTS TRANSFER (
    TransferID VARCHAR(50) PRIMARY KEY,
    LeagueID VARCHAR(50),
    FromTeamID VARCHAR(50),
    ToTeamID VARCHAR(50),
    TransferDate DATE,
    TransferType VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LeagueID) REFERENCES LEAGUE(LeagueID) ON DELETE SET NULL,
    FOREIGN KEY (FromTeamID) REFERENCES TEAM(TeamID) ON DELETE SET NULL,
    FOREIGN KEY (ToTeamID) REFERENCES TEAM(TeamID) ON DELETE SET NULL
);

-- TRANSFERDETAILS Table
CREATE TABLE IF NOT EXISTS TRANSFERDETAILS (
    TransferDetailsID VARCHAR(50) PRIMARY KEY,
    TransferID VARCHAR(50) NOT NULL,
    PlayerID VARCHAR(50) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TransferID) REFERENCES TRANSFER(TransferID) ON DELETE CASCADE,
    FOREIGN KEY (PlayerID) REFERENCES PLAYER(PlayerID) ON DELETE CASCADE
);

-- Insert default admin
INSERT INTO USERACCOUNT (UserID, Username, Password, Role) 
VALUES ('admin001', 'admin@demo.com', '$2b$10$YourHashedPasswordHere', 'Admin')
ON DUPLICATE KEY UPDATE Username=Username;

INSERT INTO ADMIN (AdminID, UserID, AdminName, Email, Password) 
VALUES ('admin001', 'admin001', 'Admin User', 'admin@demo.com', '$2b$10$YourHashedPasswordHere')
ON DUPLICATE KEY UPDATE AdminName=AdminName;

-- Insert default user
INSERT INTO USERACCOUNT (UserID, Username, Password, Role) 
VALUES ('user001', 'user@demo.com', '$2b$10$YourHashedPasswordHere', 'User')
ON DUPLICATE KEY UPDATE Username=Username;
