-- Sports Management Database Schema with AUTO_INCREMENT IDs

DROP DATABASE IF EXISTS sports_management_db;
CREATE DATABASE sports_management_db;
USE sports_management_db;

-- USERACCOUNT Table
CREATE TABLE USERACCOUNT (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role ENUM('User', 'Admin') NOT NULL DEFAULT 'User',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ADMIN Table
CREATE TABLE ADMIN (
    AdminID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    AdminName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USERACCOUNT(UserID) ON DELETE CASCADE
);

-- COACH Table
CREATE TABLE COACH (
    CoachID INT AUTO_INCREMENT PRIMARY KEY,
    CoachName VARCHAR(100) NOT NULL,
    Contact VARCHAR(50),
    Experience INT DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- REFEREE Table
CREATE TABLE REFEREE (
    RefereeID INT AUTO_INCREMENT PRIMARY KEY,
    RefereeName VARCHAR(100) NOT NULL,
    Contact VARCHAR(50),
    AvailabilityStatus ENUM('Available', 'Unavailable') DEFAULT 'Available',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- LEAGUE Table
CREATE TABLE LEAGUE (
    LeagueID INT AUTO_INCREMENT PRIMARY KEY,
    AdminID INT NOT NULL,
    LeagueName VARCHAR(100) NOT NULL,
    StartDate DATE,
    EndDate DATE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AdminID) REFERENCES ADMIN(AdminID) ON DELETE CASCADE
);

-- TOURNAMENT Table
CREATE TABLE TOURNAMENT (
    TournamentID INT AUTO_INCREMENT PRIMARY KEY,
    AdminID INT NOT NULL,
    TournamentName VARCHAR(100) NOT NULL,
    StartDate DATE,
    EndDate DATE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AdminID) REFERENCES ADMIN(AdminID) ON DELETE CASCADE
);

-- TEAM Table
CREATE TABLE TEAM (
    TeamID INT AUTO_INCREMENT PRIMARY KEY,
    LeagueID INT,
    CoachID INT,
    TeamName VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LeagueID) REFERENCES LEAGUE(LeagueID) ON DELETE SET NULL,
    FOREIGN KEY (CoachID) REFERENCES COACH(CoachID) ON DELETE SET NULL
);

-- TEAMSTATS Table (League-specific team statistics)
CREATE TABLE TEAMSTATS (
    LeagueStatsID INT AUTO_INCREMENT PRIMARY KEY,
    LeagueID INT NOT NULL,
    TeamID INT NOT NULL,
    Wins INT DEFAULT 0,
    Losses INT DEFAULT 0,
    Draws INT DEFAULT 0,
    Points INT DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LeagueID) REFERENCES LEAGUE(LeagueID) ON DELETE CASCADE,
    FOREIGN KEY (TeamID) REFERENCES TEAM(TeamID) ON DELETE CASCADE
);

-- TOURNAMENTTEAM Junction Table
CREATE TABLE TOURNAMENTTEAM (
    TournamentTeamID INT AUTO_INCREMENT PRIMARY KEY,
    TournamentID INT NOT NULL,
    TeamID INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TournamentID) REFERENCES TOURNAMENT(TournamentID) ON DELETE CASCADE,
    FOREIGN KEY (TeamID) REFERENCES TEAM(TeamID) ON DELETE CASCADE,
    UNIQUE KEY unique_tournament_team (TournamentID, TeamID)
);

-- PLAYER Table
CREATE TABLE PLAYER (
    PlayerID INT AUTO_INCREMENT PRIMARY KEY,
    TeamID INT,
    PlayerName VARCHAR(100) NOT NULL,
    PlayerRole VARCHAR(50),
    ContractDetails TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TeamID) REFERENCES TEAM(TeamID) ON DELETE SET NULL
);

-- PLAYERSTATS Table
CREATE TABLE PLAYERSTATS (
    StatsID INT AUTO_INCREMENT PRIMARY KEY,
    PlayerID INT NOT NULL,
    MatchesPlayed INT DEFAULT 0,
    Wins INT DEFAULT 0,
    GoalsOrRuns INT DEFAULT 0,
    Assists INT DEFAULT 0,
    Rating DECIMAL(3,2) DEFAULT 0.00,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PlayerID) REFERENCES PLAYER(PlayerID) ON DELETE CASCADE
);

-- VENUE Table
CREATE TABLE VENUE (
    VenueID INT AUTO_INCREMENT PRIMARY KEY,
    VenueName VARCHAR(100) NOT NULL,
    Location VARCHAR(200),
    Capacity INT,
    IsAvailable BOOLEAN DEFAULT TRUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- MATCH Table
CREATE TABLE `MATCH` (
    MatchID INT AUTO_INCREMENT PRIMARY KEY,
    LeagueID INT,
    TournamentID INT,
    VenueID INT,
    RefereeID INT,
    MatchDate DATE,
    MatchTime TIME,
    Team1Score INT DEFAULT 0,
    Team2Score INT DEFAULT 0,
    Status ENUM('Scheduled', 'Live', 'Completed', 'Cancelled') DEFAULT 'Scheduled',
    WinnerTeamID INT,
    Highlights TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LeagueID) REFERENCES LEAGUE(LeagueID) ON DELETE CASCADE,
    FOREIGN KEY (TournamentID) REFERENCES TOURNAMENT(TournamentID) ON DELETE CASCADE,
    FOREIGN KEY (VenueID) REFERENCES VENUE(VenueID) ON DELETE SET NULL,
    FOREIGN KEY (RefereeID) REFERENCES REFEREE(RefereeID) ON DELETE SET NULL,
    FOREIGN KEY (WinnerTeamID) REFERENCES TEAM(TeamID) ON DELETE SET NULL
);

-- TRANSFER Table
CREATE TABLE TRANSFER (
    TransferID INT AUTO_INCREMENT PRIMARY KEY,
    LeagueID INT NOT NULL,
    FromTeamID INT,
    ToTeamID INT,
    TransferDate DATE,
    TransferType ENUM('Loan', 'Permanent') DEFAULT 'Permanent',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LeagueID) REFERENCES LEAGUE(LeagueID) ON DELETE CASCADE,
    FOREIGN KEY (FromTeamID) REFERENCES TEAM(TeamID) ON DELETE SET NULL,
    FOREIGN KEY (ToTeamID) REFERENCES TEAM(TeamID) ON DELETE SET NULL
);

-- TRANSFERDETAILS Junction Table
CREATE TABLE TRANSFERDETAILS (
    TransferDetailsID INT AUTO_INCREMENT PRIMARY KEY,
    TransferID INT NOT NULL,
    PlayerID INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TransferID) REFERENCES TRANSFER(TransferID) ON DELETE CASCADE,
    FOREIGN KEY (PlayerID) REFERENCES PLAYER(PlayerID) ON DELETE CASCADE
);

-- Insert default admin user
INSERT INTO USERACCOUNT (Username, Password, Role) VALUES ('admin', 'admin123', 'Admin');
INSERT INTO ADMIN (UserID, AdminName, Email, Password) VALUES (1, 'System Admin', 'admin@sports.com', 'admin123');

-- Insert default regular user
INSERT INTO USERACCOUNT (Username, Password, Role) VALUES ('user', 'user123', 'User');
